(() => {
  'use strict';
  const COLUMN_KEY='uiv2.table.visibleColumns';
  const COLUMNS={name:'User',role:'Role',department:'Department',status:'Status',lastActive:'Last Active'};
  const today=new Date(), daysAgo=days=>{const date=new Date(today);date.setDate(date.getDate()-days);return date.toISOString().slice(0,10);};
  // Replace SAMPLE_RECORDS with records returned by a future PHP/API integration.
  const SAMPLE_RECORDS=[
    ['Jane Doe','jane.doe@example.com','Administrator','IT','Active',0],['John Smith','john.smith@example.com','Editor','Marketing','Pending',1],['Robert Johnson','robert.j@example.com','Viewer','Sales','Inactive',18],
    ['Maria Santos','maria.santos@example.com','Manager','Operations','Active',2],['David Lee','david.lee@example.com','Analyst','Finance','Active',4],['Angela Cruz','angela.cruz@example.com','Editor','Human Resources','Active',7],
    ['Michael Tan','michael.tan@example.com','Viewer','IT','Inactive',46],['Sofia Reyes','sofia.reyes@example.com','Manager','Marketing','Active',3],['Daniel Garcia','daniel.garcia@example.com','Analyst','Sales','Pending',12],
    ['Patricia Lim','patricia.lim@example.com','Administrator','Finance','Active',0],['Kevin Ramos','kevin.ramos@example.com','Editor','Operations','Active',21],['Bianca Flores','bianca.flores@example.com','Viewer','Human Resources','Inactive',65],
    ['Nathan Yu','nathan.yu@example.com','Analyst','IT','Active',5],['Camille Torres','camille.torres@example.com','Manager','Sales','Pending',9],['Luis Mendoza','luis.mendoza@example.com','Editor','Finance','Active',14],
    ['Erika Navarro','erika.navarro@example.com','Viewer','Marketing','Active',29],['Paolo Aquino','paolo.aquino@example.com','Analyst','Operations','Inactive',92],['Grace Villanueva','grace.v@example.com','Manager','Human Resources','Active',6]
  ].map((r,index)=>({id:index+1,name:r[0],email:r[1],role:r[2],department:r[3],status:r[4],lastActive:daysAgo(r[5]),enabled:r[4]==='Active'}));
  const $=(selector,root=document)=>root.querySelector(selector), $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
  const state={records:SAMPLE_RECORDS.map(r=>({...r})),query:'',filters:{status:'',role:'',department:'',date:'',enabled:false},sort:{key:'name',direction:'asc'},page:1,perPage:10,selected:new Set(),visible:new Set(Object.keys(COLUMNS)),mode:'loading',confirmAction:null,lastFocus:null};
  try { const stored=JSON.parse(localStorage.getItem(COLUMN_KEY)); if(Array.isArray(stored)&&stored.some(key=>COLUMNS[key])) state.visible=new Set(stored.filter(key=>COLUMNS[key])); } catch {}
  const debounce=(fn,delay=250)=>{let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),delay);};};
  const initials=name=>name.split(/\s+/).map(part=>part[0]).slice(0,2).join('').toUpperCase();
  const formatDate=value=>new Date(`${value}T00:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
  const daysSince=value=>Math.floor((new Date(today.toDateString())-new Date(`${value}T00:00:00`))/86400000);
  const displayLastActive=value=>{const days=daysSince(value);return days===0?'Today':days===1?'Yesterday':days<7?`${days} days ago`:formatDate(value);};
  const csvEscape=value=>`"${String(value??'').replace(/"/g,'""')}"`;

  function toast(message,tone='success'){const node=document.createElement('div');node.className='table-toast';node.setAttribute('role','status');if(tone==='error')node.style.borderLeftColor='var(--ui-danger)';const icon=document.createElement('span');icon.className='material-symbols-outlined';icon.textContent=tone==='error'?'error':'check_circle';const text=document.createElement('span');text.textContent=message;node.append(icon,text);$('#table-toast-container').append(node);setTimeout(()=>node.remove(),3500);}
  function getFiltered(){
    const query=state.query.trim().toLowerCase(); return state.records.filter(record=>{
      const visibleValues=[...state.visible].flatMap(key=>key==='name'?[record.name,record.email]:[record[key]]);
      if(query&&!visibleValues.some(value=>String(value).toLowerCase().includes(query)))return false;
      if(state.filters.status&&record.status!==state.filters.status)return false;if(state.filters.role&&record.role!==state.filters.role)return false;if(state.filters.department&&record.department!==state.filters.department)return false;if(state.filters.enabled&&!record.enabled)return false;
      const days=daysSince(record.lastActive);if(state.filters.date==='today'&&days!==0)return false;if(state.filters.date==='week'&&days>7)return false;if(state.filters.date==='month'&&days>30)return false;if(state.filters.date==='older'&&days<=30)return false;return true;
    }).sort((a,b)=>{let av=a[state.sort.key],bv=b[state.sort.key];if(state.sort.key==='lastActive'){av=new Date(av);bv=new Date(bv);}const result=av<bv?-1:av>bv?1:0;return state.sort.direction==='asc'?result:-result;});
  }
  function getPage(records=getFiltered()){const pages=Math.max(1,Math.ceil(records.length/state.perPage));state.page=Math.min(state.page,pages);return records.slice((state.page-1)*state.perPage,state.page*state.perPage);}
  function activeFilterEntries(){const labels={status:'Status',role:'Role',department:'Department',date:'Last active',enabled:'Activity'};return Object.entries(state.filters).filter(([,value])=>value).map(([key,value])=>[key,labels[key],key==='enabled'?'Active only':value]);}

  function render(){renderOverview();renderColumns();renderFilters();renderTable();renderBulk();renderPagination();renderSort();}
  function renderOverview(){const active=state.records.filter(record=>record.status==='Active').length,departments=new Set(state.records.map(record=>record.department)).size;$('#overview-total').textContent=state.records.length;$('#overview-active').textContent=active;$('#overview-departments').textContent=departments;}
  function renderColumns(){Object.keys(COLUMNS).forEach(key=>$$(`[data-column="${key}"]`).forEach(el=>el.hidden=!state.visible.has(key)));}
  function renderFilters(){const root=$('#filter-chips');root.replaceChildren();if(state.query){root.append(makeChip('query','Search',state.query));}activeFilterEntries().forEach(([key,label,value])=>root.append(makeChip(key,label,value)));const count=getFiltered().length;$('#match-count').textContent=`${count} matching ${count===1?'record':'records'}`;$('#clear-search').hidden=!state.query;}
  function makeChip(key,label,value){const chip=document.createElement('span');chip.className='filter-chip';chip.append(document.createTextNode(`${label}: ${value}`));const button=document.createElement('button');button.type='button';button.dataset.removeFilter=key;button.setAttribute('aria-label',`Remove ${label} filter`);const icon=document.createElement('span');icon.className='material-symbols-outlined';icon.textContent='close';button.append(icon);chip.append(button);return chip;}
  function renderTable(){
    const body=$('#records-body'),filtered=getFiltered(),pageRecords=getPage(filtered),stateBox=$('#table-state'),scroll=$('#table-scroll');body.replaceChildren();
    if(state.mode!=='success'||!pageRecords.length){scroll.hidden=true;stateBox.hidden=false;const hasRecords=state.records.length>0;let icon='hourglass_top',title='Loading records…',message='Preparing the data table.';if(state.mode==='error'){icon='error';title='Records could not be loaded';message='Check the data source and try again.';}else if(state.mode==='success'&&!hasRecords){icon='inbox';title='No records yet';message='Add a new record to get started.';}else if(state.mode==='success'){icon='search_off';title='No matching records';message='Try a different search or clear your filters.';}stateBox.replaceChildren();const i=document.createElement('span');i.className='state-icon material-symbols-outlined';i.textContent=icon;const strong=document.createElement('strong');strong.textContent=title;const p=document.createElement('p');p.textContent=message;stateBox.append(i,strong,p);if(state.mode==='error'||(state.mode==='success'&&filtered.length===0)){const button=document.createElement('button');button.type='button';button.className='button button-secondary';button.id=state.mode==='error'?'retry-load':'empty-clear';button.textContent=state.mode==='error'?'Retry':'Clear search and filters';stateBox.append(button);}return;}
    stateBox.hidden=true;scroll.hidden=false;pageRecords.forEach(record=>body.append(createRow(record)));
    const ids=pageRecords.map(r=>r.id),selectedCount=ids.filter(id=>state.selected.has(id)).length,all=ids.length&&selectedCount===ids.length;$('#select-all').checked=all;$('#select-all').indeterminate=selectedCount>0&&!all;
  }
  function createRow(record){
    const tr=document.createElement('tr');tr.dataset.id=record.id;if(state.selected.has(record.id))tr.classList.add('selected');
    const select=document.createElement('td');select.className='select-cell';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.className='row-select';checkbox.checked=state.selected.has(record.id);checkbox.dataset.id=record.id;checkbox.setAttribute('aria-label',`Select ${record.name}`);select.append(checkbox);tr.append(select);
    const name=document.createElement('td');name.dataset.column='name';const user=document.createElement('div');user.className='user-cell';const avatar=document.createElement('span');avatar.className=`user-avatar avatar-tone-${record.id%5}`;avatar.textContent=initials(record.name);const copy=document.createElement('span');copy.className='user-copy';copy.dataset.mobileMeta=`${record.role} · ${record.department} · ${record.status}`;const strong=document.createElement('strong');strong.textContent=record.name;const small=document.createElement('small');small.textContent=record.email;copy.append(strong,small);user.append(avatar,copy);name.append(user);tr.append(name);
    ['role','department'].forEach(key=>{const td=document.createElement('td');td.dataset.column=key;const value=document.createElement('span');value.className=key==='role'?'role-label':'department-label';value.textContent=record[key];td.append(value);tr.append(td);});
    const status=document.createElement('td');status.dataset.column='status';const badge=document.createElement('span');badge.className=`status-badge status-${record.status.toLowerCase()}`;badge.textContent=record.status;status.append(badge);tr.append(status);
    const active=document.createElement('td');active.dataset.column='lastActive';active.textContent=displayLastActive(record.lastActive);active.title=formatDate(record.lastActive);tr.append(active);
    const actions=document.createElement('td');actions.className='actions-cell';actions.innerHTML='<div class="row-menu-wrap"><button class="row-action" type="button" aria-label="Actions" aria-expanded="false"><span class="material-symbols-outlined">more_vert</span></button><div class="row-menu" role="menu" hidden><button type="button" role="menuitem" data-row-action="view"><span class="material-symbols-outlined">visibility</span>View Details</button><button type="button" role="menuitem" data-row-action="edit"><span class="material-symbols-outlined">edit</span>Edit</button><button type="button" role="menuitem" data-row-action="toggle"><span class="material-symbols-outlined">toggle_on</span><span class="toggle-label"></span></button><button type="button" role="menuitem" data-row-action="delete" class="danger"><span class="material-symbols-outlined">delete</span>Delete</button></div></div>';$('.row-action',actions).dataset.id=record.id;$$('[data-row-action]',actions).forEach(btn=>btn.dataset.id=record.id);$('.toggle-label',actions).textContent=record.status==='Active'?'Deactivate':'Activate';tr.append(actions);return tr;
  }
  function renderBulk(){const count=state.selected.size;$('#bulk-toolbar').hidden=count===0;$('#selection-count').textContent=`${count} ${count===1?'record':'records'} selected`;}
  function renderPagination(){const filtered=getFiltered(),pages=Math.max(1,Math.ceil(filtered.length/state.perPage)),nav=$('#pagination');nav.replaceChildren();const create=(label,page,disabled=false,current=false)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.page=page;b.disabled=disabled;if(current){b.className='current';b.setAttribute('aria-current','page');}return b;};nav.append(create('‹',state.page-1,state.page===1));for(let page=1;page<=pages;page++){if(pages>7&&page>2&&page<pages-1&&Math.abs(page-state.page)>1){if(!nav.lastElementChild?.classList.contains('ellipsis')){const span=document.createElement('span');span.className='ellipsis';span.textContent='…';nav.append(span);}continue;}nav.append(create(String(page),page,false,page===state.page));}nav.append(create('›',state.page+1,state.page===pages));const start=filtered.length?(state.page-1)*state.perPage+1:0,end=Math.min(state.page*state.perPage,filtered.length);$('#pagination-summary').textContent=`Showing ${start}–${end} of ${filtered.length}`;}
  function renderSort(){$$('.sort-button').forEach(button=>{const active=button.dataset.sort===state.sort.key;button.classList.toggle('active',active);button.setAttribute('aria-label',`Sort by ${button.textContent.trim()}${active?`, ${state.sort.direction}ending`:''}`);$('span',button).textContent=active?(state.sort.direction==='asc'?'arrow_upward':'arrow_downward'):'unfold_more';});}

  function populateOptions(){const fill=(id,key)=>{const select=$(`#${id}`);[...new Set(state.records.map(r=>r[key]))].sort().forEach(value=>{const option=document.createElement('option');option.value=option.textContent=value;select.append(option);});};fill('filter-role','role');fill('filter-department','department');const root=$('#column-options');Object.entries(COLUMNS).forEach(([key,label])=>{const row=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.checked=state.visible.has(key);input.dataset.columnOption=key;row.append(input,document.createTextNode(label));root.append(row);});}
  function togglePopover(id,buttonId){const panel=$(`#${id}`),open=panel.hidden;closePopovers(id);panel.hidden=!open;$(`#${buttonId}`).setAttribute('aria-expanded',String(open));if(open)$('select,input',panel)?.focus();}
  function closePopovers(except){[['filter-panel','filter-toggle'],['column-panel','column-toggle']].forEach(([panel,button])=>{if(panel!==except){$(`#${panel}`).hidden=true;$(`#${button}`).setAttribute('aria-expanded','false');}});$$('.row-menu').forEach(menu=>menu.hidden=true);$$('.row-action').forEach(btn=>btn.setAttribute('aria-expanded','false'));}
  function resetFilters(){state.query='';$('#table-search').value='';Object.keys(state.filters).forEach(key=>state.filters[key]=key==='enabled'?false:'');['status','role','department','date'].forEach(key=>$(`#filter-${key}`).value='');$('#filter-enabled').checked=false;state.page=1;render();}
  function applyFilterInput(target){const key=target.id.replace('filter-','');state.filters[key]=target.type==='checkbox'?target.checked:target.value;state.page=1;render();}

  function openModal(id){const modal=$(`#${id}`);state.lastFocus=document.activeElement;modal.hidden=false;requestAnimationFrame(()=>$('input,select,button',modal)?.focus());}
  function closeModal(modal=$('.table-modal:not([hidden])')){if(!modal)return;modal.hidden=true;state.confirmAction=null;state.lastFocus?.focus();}
  function openRecordForm(record){$('#record-form').reset();$$('.field-error').forEach(e=>e.textContent='');$$('.invalid').forEach(e=>e.classList.remove('invalid'));$('#record-id').value=record?.id||'';$('#record-modal-title').textContent=record?'Edit Record':'New Record';if(record){['name','email','role','department','status','lastActive'].forEach(key=>$(`#record-${key.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`)}`).value=record[key]);}else{$('#record-status').value='Active';$('#record-last-active').value=daysAgo(0);}openModal('record-modal');}
  function validateForm(){const values={};let valid=true;['name','email','role','department','status','lastActive'].forEach(key=>{const id=key.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`),input=$(`#record-${id}`),value=input.value.trim();values[key]=value;let error='';if(!value)error='This field is required.';if(key==='name'&&value&&value.length<2)error='Enter at least 2 characters.';if(key==='email'&&value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))error='Enter a valid email address.';if(key==='email'&&state.records.some(r=>r.email.toLowerCase()===value.toLowerCase()&&String(r.id)!==$('#record-id').value))error='This email is already in use.';$(`[data-error="${key}"]`).textContent=error;input.classList.toggle('invalid',!!error);if(error)valid=false;});return valid?values:null;}
  function submitRecord(event){event.preventDefault();const values=validateForm();if(!values){toast('Please correct the highlighted fields.','error');return;}const id=Number($('#record-id').value);if(id){const record=state.records.find(r=>r.id===id);Object.assign(record,values,{enabled:values.status==='Active'});toast(`${record.name} updated successfully.`);}else{const record={id:Math.max(0,...state.records.map(r=>r.id))+1,...values,enabled:values.status==='Active'};state.records.unshift(record);toast(`${record.name} added successfully.`);}state.mode='success';closeModal();state.page=1;refreshFilterOptions();render();}
  function refreshFilterOptions(){['filter-role','filter-department'].forEach(id=>{const select=$(`#${id}`),value=select.value;while(select.options.length>1)select.remove(1);const key=id.replace('filter-','');[...new Set(state.records.map(r=>r[key]))].sort().forEach(item=>select.add(new Option(item,item)));select.value=value;});}
  function showDetails(record){const root=$('#detail-content');root.replaceChildren();Object.entries({Name:record.name,Email:record.email,Role:record.role,Department:record.department,Status:record.status,'Last Active':formatDate(record.lastActive)}).forEach(([label,value])=>{const item=document.createElement('div');item.className='detail-item';const small=document.createElement('small');small.textContent=label;const strong=document.createElement('strong');strong.textContent=value;item.append(small,strong);root.append(item);});openModal('detail-modal');}
  function confirmDelete(message,action){$('#confirm-message').textContent=message;state.confirmAction=action;openModal('confirm-modal');}
  function deleteIds(ids){state.records=state.records.filter(r=>!ids.includes(r.id));ids.forEach(id=>state.selected.delete(id));state.mode='success';refreshFilterOptions();render();toast(`${ids.length} ${ids.length===1?'record':'records'} deleted.`);}
  function exportCsv(selectedOnly=false){const source=selectedOnly?state.records.filter(r=>state.selected.has(r.id)):getFiltered();if(!source.length){toast('There are no records to export.','error');return;}const keys=[...state.visible],headers=keys.map(key=>COLUMNS[key]),rows=source.map(record=>keys.map(key=>key==='name'?`${record.name} <${record.email}>`:record[key]));const csv=[headers,...rows].map(row=>row.map(csvEscape).join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=selectedOnly?'selected-records.csv':'filtered-records.csv';link.click();URL.revokeObjectURL(link.href);toast(`${source.length} records exported.`);}
  function bulkAction(action){const ids=[...state.selected];if(!ids.length)return;if(action==='export'){exportCsv(true);return;}if(action==='delete'){confirmDelete(`Delete ${ids.length} selected records? This action cannot be undone.`,()=>deleteIds(ids));return;}const status=action==='activate'?'Active':'Inactive';state.records.filter(r=>state.selected.has(r.id)).forEach(r=>{r.status=status;r.enabled=status==='Active';});render();toast(`${ids.length} records set to ${status.toLowerCase()}.`);}
  function rowAction(action,id){const record=state.records.find(r=>r.id===id);if(!record)return;closePopovers();if(action==='view')showDetails(record);if(action==='edit')openRecordForm(record);if(action==='toggle'){record.status=record.status==='Active'?'Inactive':'Active';record.enabled=record.status==='Active';render();toast(`${record.name} ${record.status.toLowerCase()}.`);}if(action==='delete')confirmDelete(`Delete ${record.name}? This action cannot be undone.`,()=>deleteIds([id]));}

  function init(){
    populateOptions();render();setTimeout(()=>{state.mode='success';render();toast('Records loaded successfully.');},250);
    $('#table-search').addEventListener('input',debounce(event=>{state.query=event.target.value;state.page=1;render();}));$('#clear-search').addEventListener('click',()=>{state.query='';$('#table-search').value='';state.page=1;render();$('#table-search').focus();});
    $('#filter-toggle').addEventListener('click',()=>togglePopover('filter-panel','filter-toggle'));$('#add-filter').addEventListener('click',()=>togglePopover('filter-panel','filter-toggle'));$('#column-toggle').addEventListener('click',()=>togglePopover('column-panel','column-toggle'));$('#clear-filters').addEventListener('click',resetFilters);$$('#filter-panel select,#filter-panel input').forEach(input=>input.addEventListener('change',event=>applyFilterInput(event.target)));
    $('#new-record').addEventListener('click',()=>openRecordForm());$('#record-form').addEventListener('submit',submitRecord);$('#export-csv').addEventListener('click',()=>exportCsv(state.selected.size>0));$('#rows-per-page').addEventListener('change',event=>{state.perPage=Number(event.target.value);state.page=1;render();});
    $('#select-all').addEventListener('change',event=>{getPage().forEach(record=>event.target.checked?state.selected.add(record.id):state.selected.delete(record.id));render();});
    document.addEventListener('change',event=>{if(event.target.matches('.row-select')){const id=Number(event.target.dataset.id);event.target.checked?state.selected.add(id):state.selected.delete(id);render();}if(event.target.matches('[data-column-option]')){const key=event.target.dataset.columnOption;if(event.target.checked)state.visible.add(key);else if(state.visible.size===1){event.target.checked=true;toast('At least one data column must remain visible.','error');return;}else state.visible.delete(key);localStorage.setItem(COLUMN_KEY,JSON.stringify([...state.visible]));state.page=1;render();}});
    document.addEventListener('click',event=>{
      if(!event.target.closest('.popover-wrap')&&!event.target.closest('.row-menu-wrap'))closePopovers();
      const sort=event.target.closest('[data-sort]');if(sort){const key=sort.dataset.sort;state.sort.direction=state.sort.key===key&&state.sort.direction==='asc'?'desc':'asc';state.sort.key=key;state.page=1;render();}
      const remove=event.target.closest('[data-remove-filter]');if(remove){const key=remove.dataset.removeFilter;if(key==='query'){state.query='';$('#table-search').value='';}else{state.filters[key]=key==='enabled'?false:'';const input=$(`#filter-${key}`);if(input)input.type==='checkbox'?input.checked=false:input.value='';}state.page=1;render();}
      const page=event.target.closest('[data-page]');if(page&&!page.disabled){state.page=Number(page.dataset.page);render();$('#records-table').focus?.();}
      const rowButton=event.target.closest('.row-action');if(rowButton){const menu=rowButton.nextElementSibling,open=menu.hidden;closePopovers();menu.hidden=!open;rowButton.setAttribute('aria-expanded',String(open));}
      const action=event.target.closest('[data-row-action]');if(action)rowAction(action.dataset.rowAction,Number(action.dataset.id));
      const bulk=event.target.closest('[data-bulk]');if(bulk)bulkAction(bulk.dataset.bulk);
      const close=event.target.closest('[data-close-modal]');if(close)closeModal(close.closest('.table-modal'));
      if(event.target.classList.contains('table-modal'))closeModal(event.target);
      if(event.target.id==='empty-clear')resetFilters();if(event.target.id==='retry-load'){state.mode='loading';render();setTimeout(()=>{state.mode='success';render();toast('Records loaded successfully.');},400);}
    });
    $('#confirm-action').addEventListener('click',()=>{const action=state.confirmAction;closeModal();action?.();});
    document.addEventListener('keydown',event=>{if(event.key==='Escape'){closePopovers();closeModal();}const modal=event.target.closest?.('.table-modal');if(event.key==='Tab'&&modal&&!modal.hidden){const focusable=$$('button:not([disabled]),input:not([type="hidden"]),select',modal);const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
  }
  document.addEventListener('DOMContentLoaded',init);
})();
