(() => {
  'use strict';

  const STORAGE = { subsystem:'uiv2.dashboard.subsystem', sidebar:'uiv2.dashboard.sidebarCollapsed' };
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const escapeCsv = value => `"${String(value ?? '').replace(/"/g, '""')}"`;
  const subsystemIcons = {
    'client-management':'groups','hris':'badge','employee-development':'school','governance-safety':'shield',
    'financial-management':'account_balance_wallet','supply-chain':'inventory_2','fleet-management':'local_shipping',
    facilities:'apartment','business-intelligence':'monitoring','crm-sales':'handshake'
  };
  const subsystemColors = {
    'client-management':['#db2777','#fdf2f8'], hris:['#2563eb','#eff6ff'],
    'employee-development':['#7c3aed','#f5f3ff'], 'governance-safety':['#0891b2','#ecfeff'],
    'financial-management':['#059669','#ecfdf5'], 'supply-chain':['#d97706','#fffbeb'],
    'fleet-management':['#dc2626','#fef2f2'], facilities:['#475569','#f8fafc'],
    'business-intelligence':['#eec643','#fffbea','#1f1d26','#4a3820'], 'crm-sales':['#0f766e','#f0fdfa']
  };
  const actionIcons = ['add_box','task_alt','sync','analytics','download'];
  const state = { subsystemId:null, activityPage:1, activityPerPage:5, showAll:false, lastFocus:null };

  function availableSubsystems() { return typeof SUBSYSTEMS !== 'undefined' && Array.isArray(SUBSYSTEMS) ? SUBSYSTEMS : []; }
  function querySubsystem() { return new URLSearchParams(location.search).get('subsystem'); }
  function getSubsystem() { return availableSubsystems().find(item => item.id === state.subsystemId) || availableSubsystems()[0]; }
  function moduleName(item) { return typeof item === 'string' ? item : item.name; }
  function iconForModule(name) {
    const value = String(name).toLowerCase();
    const rules = [['payroll|ledger|budget|cash|account|tax','payments'],['report|analytic|dashboard|kpi|performance','monitoring'],['vehicle|fleet|driver|route|transport','local_shipping'],['warehouse|inventory|asset|equipment','inventory_2'],['document|contract|record','description'],['health|safety|legal|compliance','verified_user'],['employee|applicant|client|visitor|lead|supplier','groups'],['time|leave|reservation|schedule|follow-up','calendar_month'],['training|development','school'],['system administration|security','admin_panel_settings'],['facility|room','apartment']];
    return rules.find(([pattern]) => new RegExp(pattern).test(value))?.[1] || 'apps';
  }
  function numericValue(value, fallback = 68) { const number = parseFloat(String(value).replace(/[^0-9.-]/g,'')); if(!Number.isFinite(number))return fallback; return number>100?72+(Math.round(number)%23):Math.max(12,Math.min(100,Math.round(number))); }
  function toneClass(tone) { return tone === 'caution' ? 'warning' : tone === 'negative' ? 'danger' : ''; }
  function statusClass(status) { const value=String(status).toLowerCase(); if(/alert|failed|incident|conflict/.test(value))return 'status-danger'; if(/pending|queued|caution|new|transit|progress/.test(value))return 'status-warning'; if(/updated|scheduled|published|validated/.test(value))return 'status-info'; return 'status-success'; }

  function toast(message, tone='success') {
    const node=document.createElement('div'); node.className='dash-toast'; node.setAttribute('role','status'); if(tone==='danger')node.style.borderLeftColor='var(--ui-danger)';
    const icon=document.createElement('span'); icon.className='material-symbols-outlined'; icon.textContent=tone==='danger'?'error':'check_circle'; const text=document.createElement('span'); text.textContent=message; node.append(icon,text); $('#dash-toast-container').append(node); setTimeout(()=>node.remove(),3500);
  }
  function toggleSidebar() { if(innerWidth<=900)document.body.classList.toggle('mobile-sidebar-open'); else { const collapsed=document.body.classList.toggle('sidebar-collapsed'); localStorage.setItem(STORAGE.sidebar,String(collapsed)); } syncSidebar(); }
  function syncSidebar() { const mobile=innerWidth<=900, open=mobile?document.body.classList.contains('mobile-sidebar-open'):!document.body.classList.contains('sidebar-collapsed'); const button=$('#desktop-sidebar-toggle'); button.setAttribute('aria-expanded',String(open)); button.setAttribute('aria-label',mobile?`${open?'Close':'Open'} navigation`:`${open?'Collapse':'Expand'} sidebar`); $('#sidebar-toggle-icon').textContent=mobile?(open?'close':'menu'):(open?'menu_open':'menu'); }
  function closeDropdowns(except) { [['notification-menu','notification-toggle'],['profile-dropdown-menu','profile-dropdown-toggle']].forEach(([menu,button])=>{if(menu!==except){$(`#${menu}`).hidden=true;$(`#${button}`).setAttribute('aria-expanded','false');}}); $$('.activity-menu').forEach(menu=>menu.hidden=true); }
  function toggleDropdown(menuId, buttonId) { const menu=$(`#${menuId}`), open=menu.hidden; closeDropdowns(menuId); menu.hidden=!open; $(`#${buttonId}`).setAttribute('aria-expanded',String(open)); if(open)$('button,[href]',menu)?.focus(); }
  function openModal(id) { const modal=$(`#${id}`); state.lastFocus=document.activeElement; modal.hidden=false; document.body.style.overflow='hidden'; requestAnimationFrame(()=>$('button,input,select,[href]',modal)?.focus()); }
  function closeModal(modal=$('.dash-modal:not([hidden])')) { if(!modal)return; modal.hidden=true; document.body.style.overflow=''; state.lastFocus?.focus(); }
  function showAction(title, description=`This is the demonstration workflow for ${title}. Connect Continue to the appropriate ISMERS controller or API.`) { $('#action-modal-title').textContent=title; const body=$('#action-modal-body'); body.replaceChildren(); const p=document.createElement('p'); p.textContent=description; body.append(p); $('#action-confirm').dataset.action=title; openModal('action-modal'); }

  function selectSubsystem(id, announce=true) {
    const subsystem=availableSubsystems().find(item=>item.id===id) || availableSubsystems()[0]; if(!subsystem)return;
    state.subsystemId=subsystem.id; localStorage.setItem(STORAGE.subsystem,subsystem.id); history.replaceState(null,'',`${location.pathname}?subsystem=${encodeURIComponent(subsystem.id)}`);
    state.activityPage=1; state.showAll=false; renderDashboard(); if(announce)toast(`${subsystem.title} dashboard loaded.`);
  }
  function renderDashboard() {
    const subsystem=getSubsystem(); if(!subsystem)return;
    const colors=subsystemColors[subsystem.id]||['#4f46e5','#eef2ff']; document.body.style.setProperty('--subsystem-accent',colors[0]); document.body.style.setProperty('--subsystem-soft',colors[1]); if(colors[2]){document.body.style.setProperty('--subsystem-gradient-start',colors[2]);document.body.style.setProperty('--subsystem-gradient-end',colors[3]);document.body.classList.add('subsystem-dual-tone');}else{document.body.style.removeProperty('--subsystem-gradient-start');document.body.style.removeProperty('--subsystem-gradient-end');document.body.classList.remove('subsystem-dual-tone');} $('.sidebar-brand-icon').textContent=subsystemIcons[subsystem.id]||'hub';
    document.title=`${subsystem.title} — ISMERS Dashboard`; $('#sidebar-brand-title').textContent=subsystem.title; $('#sidebar-brand-category').textContent=subsystem.category; $('#breadcrumb-category').textContent=subsystem.title;
    $('#dashboard-copy').textContent=`Here’s what’s happening across ${subsystem.title} today.`; renderSidebarModules(subsystem); renderStats(subsystem); renderMonitoring(subsystem); renderQuickActions(subsystem); renderActivities(); renderSubsystemGrid();
  }
  function renderSidebarModules(subsystem) {
    const root=$('#sidebar-subsystem-modules-nav'); root.replaceChildren(); subsystem.modules.forEach((item,index)=>{ const name=moduleName(item), link=document.createElement('a'); link.href='#'; link.className='sidebar-subsystem-link'; link.dataset.tooltip=name; link.dataset.demo=name;
      const icon=document.createElement('span'); icon.className='sidebar-subsystem-link-icon material-symbols-outlined'; icon.textContent=iconForModule(name); const label=document.createElement('span'); label.className='sidebar-label'; label.textContent=name; link.append(icon,label); root.append(link); });
    $('#sidebar-subsystem-nav-panel').hidden=false;
  }
  function renderStats(subsystem) {
    const root=$('#dashboard-stats-grid'); root.replaceChildren(); subsystem.stats.forEach(stat=>{ const card=document.createElement('article'); card.className='stat-card'; const trend=stat.tone==='positive'?'Operational and on track':stat.tone==='caution'?'Needs review':'Current total'; card.setAttribute('aria-label',`${stat.label}: ${stat.value}. ${trend}`);
      card.innerHTML='<div class="stat-top"><span class="stat-label"></span><span class="stat-icon material-symbols-outlined" aria-hidden="true"></span></div><p class="stat-value"></p><span class="stat-trend"></span>'; $('.stat-label',card).textContent=stat.label; $('.stat-icon',card).textContent=stat.icon||'insights'; $('.stat-value',card).textContent=stat.value; const status=$('.stat-trend',card), tone=toneClass(stat.tone); status.textContent=trend; if(tone)status.classList.add(tone); root.append(card); });
  }
  function renderMonitoring(subsystem) {
    const values=subsystem.stats.map((stat,index)=>[stat.label,numericValue(stat.value,72-index*5),toneClass(stat.tone)]); const overview=$('#dashboard-chart-overview'), breakdown=$('#dashboard-chart-breakdown'); overview.innerHTML='<div class="monitor-title"><div><p class="section-eyebrow">Subsystem health</p><h3>Operational monitoring</h3><p>Live readiness indicators for the selected ISMERS subsystem</p></div><span class="material-symbols-outlined stat-icon">monitoring</span></div><div class="monitoring-bars"></div>';
    const bars=$('.monitoring-bars',overview); values.slice(0,3).forEach(([label,value,tone])=>{ const row=document.createElement('div'); row.className='monitor-row'; row.innerHTML='<div class="monitor-meta"><span></span><strong></strong></div><div class="progress-track"><div class="progress-fill"></div></div>'; $('.monitor-meta span',row).textContent=label; $('.monitor-meta strong',row).textContent=`${value}%`; const fill=$('.progress-fill',row); fill.style.width=`${value}%`; if(tone)fill.classList.add(tone); bars.append(row); });
    const moduleCount=subsystem.modules.length, activityCount=subsystem.activity.length; breakdown.innerHTML='<div class="monitor-title"><div><p class="section-eyebrow">Coverage</p><h3>Subsystem summary</h3><p>Connected modules and recent operational records</p></div><span class="material-symbols-outlined stat-icon">account_tree</span></div><div class="conflict-summary"><div class="conflict-metric"><strong></strong><span>Connected modules</span></div><div class="conflict-metric"><strong></strong><span>Activity records</span></div><div class="conflict-metric"><strong></strong><span>Quick actions</span></div><div class="conflict-metric"><strong></strong><span>System status</span></div></div>';
    const summary=[moduleCount,activityCount,subsystem.quickActions.length,'Online']; $$('.conflict-metric strong',breakdown).forEach((element,index)=>element.textContent=summary[index]);
  }
  function renderQuickActions(subsystem) { const root=$('#dashboard-quick-actions-list'); root.replaceChildren(); subsystem.quickActions.forEach((action,index)=>{ const button=document.createElement('button'); button.type='button'; button.className='quick-action-button'; button.dataset.quickAction=action; const icon=document.createElement('span'); icon.className='material-symbols-outlined'; icon.textContent=actionIcons[index%actionIcons.length]; const label=document.createElement('span'); label.textContent=action; const small=document.createElement('small'); small.textContent='Open workflow'; button.append(icon,label,small); root.append(button); }); }
  function renderActivities(mode='success') {
    const subsystem=getSubsystem(), records=subsystem.activity, stateBox=$('#activity-state'), wrap=$('#activity-table-wrap');
    if(mode!=='success'){wrap.hidden=true;stateBox.hidden=false;stateBox.textContent=mode==='loading'?'Loading activity…':mode==='error'?'Activity could not be loaded. Please try again.':'No recent activity is available.';return;} stateBox.hidden=true;wrap.hidden=false;
    const totalPages=Math.max(1,Math.ceil(records.length/state.activityPerPage)); state.activityPage=Math.min(state.activityPage,totalPages); const items=state.showAll?records:records.slice((state.activityPage-1)*state.activityPerPage,state.activityPage*state.activityPerPage); const tbody=$('#dashboard-activity-tbody'); tbody.replaceChildren();
    items.forEach(item=>{ const row=document.createElement('tr'); row.innerHTML='<td><span class="activity-title-cell"><strong></strong><small></small></span></td><td><span class="status-badge"></span></td><td></td><td><div class="row-menu-wrap"><button class="row-action" type="button" aria-label="Activity actions" aria-expanded="false"><span class="material-symbols-outlined">more_horiz</span></button><div class="activity-menu" role="menu" hidden><button type="button" role="menuitem">View details</button><button type="button" role="menuitem">Open record</button></div></div></td>'; $('.activity-title-cell strong',row).textContent=item.label; $('.activity-title-cell small',row).textContent=`${subsystem.title} activity`; const badge=$('.status-badge',row); badge.textContent=item.status; badge.classList.add(statusClass(item.status)); row.children[2].textContent=item.time; $$('.activity-menu button',row).forEach(button=>button.dataset.activityAction=item.label); tbody.append(row); });
    const start=records.length?(state.showAll?1:(state.activityPage-1)*state.activityPerPage+1):0, end=state.showAll?records.length:Math.min(state.activityPage*state.activityPerPage,records.length); $('#activity-count').textContent=`Showing ${start}–${end} of ${records.length} activities`; $('#activity-page').textContent=state.showAll?'All activities':`Page ${state.activityPage} of ${totalPages}`; $('#activity-prev').disabled=state.showAll||state.activityPage===1; $('#activity-next').disabled=state.showAll||state.activityPage===totalPages; $('#activity-view-all').textContent=state.showAll?'Show pages':'View All →';
  }
  function renderSubsystemGrid() { const root=$('#module-grid'); root.replaceChildren(); availableSubsystems().forEach(subsystem=>{ const button=document.createElement('button'); button.type='button'; button.className=`module-option${subsystem.id===state.subsystemId?' selected':''}`; button.dataset.moduleId=subsystem.id; const colors=subsystemColors[subsystem.id]||['#4f46e5','#eef2ff']; button.style.setProperty('--module-accent',colors[0]); button.style.setProperty('--module-soft',colors[1]); if(colors[2]){button.classList.add('dual-tone');button.style.setProperty('--module-gradient',`linear-gradient(135deg,${colors[2]},${colors[3]})`);} const icon=document.createElement('span'); icon.className='module-option-icon material-symbols-outlined'; icon.textContent=subsystemIcons[subsystem.id]||'hub'; const copy=document.createElement('span'), title=document.createElement('strong'), small=document.createElement('small'); title.textContent=subsystem.title; small.textContent=`${subsystem.category} · ${subsystem.modules.length} modules`; copy.append(title,small); button.append(icon,copy); root.append(button); }); }
  function exportReport() { const subsystem=getSubsystem(), rows=[['Subsystem',subsystem.title],['Category',subsystem.category],[],['Metric','Value'],...subsystem.stats.map(stat=>[stat.label,stat.value]),[],['Modules'],...subsystem.modules.map(item=>[moduleName(item)])]; const csv=rows.map(row=>row.map(escapeCsv).join(',')).join('\r\n'); const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}), link=document.createElement('a'); link.href=URL.createObjectURL(blob); link.download=`${subsystem.id}-dashboard-report.csv`; link.click(); URL.revokeObjectURL(link.href); toast('Subsystem report exported.'); }
  function updateClock() { const now=new Date(), clock=$('#current-time'); if(!clock)return; clock.textContent=now.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true}); clock.dateTime=now.toISOString(); }

  function init() {
    const systems=availableSubsystems(); if(!systems.length){$('#data-status').textContent='Subsystem data unavailable';return;} const requested=querySubsystem(), saved=localStorage.getItem(STORAGE.subsystem); state.subsystemId=systems.some(item=>item.id===requested)?requested:systems.some(item=>item.id===saved)?saved:systems[0].id;
    if(localStorage.getItem(STORAGE.sidebar)==='true'&&innerWidth>900)document.body.classList.add('sidebar-collapsed'); const now=new Date(), formatted=now.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'}); $('#current-date').textContent=formatted; $('#welcome-date').textContent=formatted; $('#footer-year').textContent=now.getFullYear(); updateClock(); setInterval(updateClock,1000); selectSubsystem(state.subsystemId,false); syncSidebar();
    $('#desktop-sidebar-toggle').addEventListener('click',toggleSidebar); $('#sidebar-backdrop').addEventListener('click',()=>{document.body.classList.remove('mobile-sidebar-open');syncSidebar();}); ['module-selector-trigger','change-module'].forEach(id=>$(`#${id}`).addEventListener('click',()=>openModal('module-modal')));
    $('#notification-toggle').addEventListener('click',()=>toggleDropdown('notification-menu','notification-toggle')); $('#profile-dropdown-toggle').addEventListener('click',()=>toggleDropdown('profile-dropdown-menu','profile-dropdown-toggle')); $('#mark-read').addEventListener('click',()=>{$('.notification-dot').hidden=true;toast('All notifications marked as read.');closeDropdowns();});
    $('#export-report').addEventListener('click',exportReport); $('#new-transaction').addEventListener('click',()=>showAction(`New ${getSubsystem().title} transaction`)); $('#activity-prev').addEventListener('click',()=>{state.activityPage--;renderActivities();}); $('#activity-next').addEventListener('click',()=>{state.activityPage++;renderActivities();}); $('#activity-view-all').addEventListener('click',()=>{state.showAll=!state.showAll;renderActivities();}); $('#action-confirm').addEventListener('click',event=>{const action=event.currentTarget.dataset.action||'Action';closeModal();toast(`${action} demo completed.`);});
    document.addEventListener('click',event=>{ if(!event.target.closest('.dropdown-wrap'))closeDropdowns(); const module=event.target.closest('[data-module-id]');if(module){selectSubsystem(module.dataset.moduleId);closeModal();} const close=event.target.closest('[data-close-modal]');if(close)closeModal(close.closest('.dash-modal')); const quick=event.target.closest('[data-quick-action]');if(quick)showAction(quick.dataset.quickAction); const demo=event.target.closest('[data-demo]');if(demo){event.preventDefault();showAction(demo.dataset.demo);} const profile=event.target.closest('[data-profile-action]');if(profile){closeDropdowns();showAction(profile.dataset.profileAction);} const rowAction=event.target.closest('.row-action');if(rowAction){const menu=rowAction.nextElementSibling,open=menu.hidden;closeDropdowns();menu.hidden=!open;rowAction.setAttribute('aria-expanded',String(open));} const activity=event.target.closest('[data-activity-action]');if(activity){closeDropdowns();showAction(activity.textContent,activity.dataset.activityAction);} if(event.target.classList.contains('dash-modal'))closeModal(event.target); });
    $('#sign-out-action').addEventListener('click',()=>{closeDropdowns();showAction('Sign Out','Connect Continue to the production ISMERS authentication logout route.');}); addEventListener('resize',()=>{if(innerWidth>900)document.body.classList.remove('mobile-sidebar-open');syncSidebar();}); document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeDropdowns();closeModal();document.body.classList.remove('mobile-sidebar-open');syncSidebar();}const modal=event.target.closest?.('.dash-modal');if(event.key==='Tab'&&modal&&!modal.hidden){const focusable=$$('button:not([disabled]),input,select,[href]',modal),first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
  }
  document.addEventListener('DOMContentLoaded',init);
})();
